# Generated by Django 3.2.3 on 2021-11-29 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('empid', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('regnum', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('dob', models.DateField()),
                ('aadhar', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('ystudy', models.CharField(max_length=10)),
                ('school', models.TextField()),
                ('fname', models.CharField(max_length=40)),
                ('mname', models.CharField(max_length=40)),
                ('foccupation', models.CharField(max_length=100)),
                ('moccupation', models.CharField(max_length=100)),
                ('contact', models.BigIntegerField()),
                ('password', models.CharField(max_length=40)),
                ('image', models.ImageField(upload_to='images/profilepic/%y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('examdate', models.DateField()),
                ('courseid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Dashboard.course')),
                ('studentid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Dashboard.student')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='staffid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Dashboard.staff'),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edate', models.DateField()),
                ('present', models.BooleanField(default=False)),
                ('late', models.BooleanField(default=False)),
                ('studentid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Dashboard.student')),
            ],
        ),
    ]
