# Generated by Django 3.2.3 on 2022-04-23 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='timetable',
            field=models.ImageField(null=True, upload_to='images/timetable/'),
        ),
    ]
