# Generated by Django 3.2.3 on 2022-04-23 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0002_student_timetable'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='FeeDate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='FeeDuestatus',
            field=models.BooleanField(default=True),
        ),
    ]
