# Generated by Django 3.2.3 on 2022-04-23 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0003_auto_20220423_1206'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='FeeDuestatus',
            new_name='FeeDue',
        ),
    ]
