# Generated by Django 3.2.3 on 2022-05-28 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0004_rename_feeduestatus_student_feedue'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='DateofJoin',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='FeeAmount',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='WhatsappNo',
            field=models.BigIntegerField(null=True),
        ),
    ]
