# Generated by Django 6.0.1 on 2026-09-25 09:18

import django.db.models.deletion
from django.db import migrations, models


def _dedupe_attendance(apps, schema_editor):
    """Drop duplicate attendance rows before the unique constraint is applied.

    The old schema allowed several rows for the same student on the same date.
    AlterUniqueTogether would fail outright on such data, taking the whole
    deploy down, and this migration has never run against the production
    database. Keep the highest id per (student, date) -- the most recent entry
    -- and delete the rest.
    """
    Attendance = apps.get_model('Dashboard', 'Attendance')
    seen, doomed = set(), []
    for pk, student, date in Attendance.objects.order_by('-id').values_list('id', 'studentid', 'edate'):
        key = (student, date)
        if key in seen:
            doomed.append(pk)
        else:
            seen.add(key)
    if doomed:
        Attendance.objects.filter(pk__in=doomed).delete()


def _noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0005_auto_20220528_1646'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['-edate']},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('no_class', 'No Class')], default='present', max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='active_status',
            field=models.CharField(choices=[('active', 'Active'), ('discontinued', 'Discontinued'), ('rejoining', 'Re-Joining')], default='active', max_length=15),
        ),
        migrations.AddField(
            model_name='student',
            name='branch',
            field=models.CharField(blank=True, choices=[('wcc_r', 'WCC R'), ('wcc_g', 'WCC G'), ('wcc_a', 'WCC A')], max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='category',
            field=models.CharField(blank=True, choices=[('regular', 'Regular Tuition'), ('neet', 'NEET'), ('vac', 'Value-Added Course'), ('daycare', 'Day Care'), ('spoken', 'Spoken English')], max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='curriculum',
            field=models.CharField(blank=True, choices=[('state', 'State Board'), ('cbse', 'CBSE'), ('icse', 'ICSE'), ('igcse', 'IGCSE')], max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='father_mobile',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='father_whatsapp',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='mother_mobile',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='mother_whatsapp',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='std',
            field=models.CharField(blank=True, choices=[('KG', 'KG'), ('LKG', 'LKG'), ('UKG', 'UKG'), ('I', 'I'), ('II', 'II'), ('III', 'III'), ('IV', 'IV'), ('V', 'V'), ('VI', 'VI'), ('VII', 'VII'), ('VIII', 'VIII'), ('IX', 'IX'), ('X', 'X'), ('XI', 'XI'), ('XII', 'XII')], max_length=5, verbose_name='Class / STD'),
        ),
        migrations.AddField(
            model_name='student',
            name='team',
            field=models.CharField(blank=True, choices=[('ripplers', 'Ripplers'), ('planners', 'Planners')], max_length=15),
        ),
        migrations.RunPython(_dedupe_attendance, _noop),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('studentid', 'edate')},
        ),
        migrations.CreateModel(
            name='FeeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(help_text='e.g. 2026-27', max_length=9)),
                ('fee_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('admission_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('admission_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('jersey_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('material_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('updated_on', models.DateField(auto_now=True)),
                ('remarks', models.CharField(blank=True, max_length=200)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_records', to='Dashboard.student')),
            ],
            options={
                'ordering': ['-academic_year', 'student__name'],
                'unique_together': {('student', 'academic_year')},
            },
        ),
        migrations.CreateModel(
            name='MarkEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_type', models.CharField(choices=[('internal', 'Internal'), ('external', 'External')], default='internal', max_length=10)),
                ('exam_name', models.CharField(blank=True, max_length=60)),
                ('examdate', models.DateField()),
                ('mark', models.DecimalField(decimal_places=2, max_digits=6)),
                ('out_of', models.DecimalField(decimal_places=2, default=100, max_digits=6)),
                ('pass_mark_percent', models.PositiveSmallIntegerField(default=35, help_text='Percentage at or above which the result counts as a pass.')),
                ('faculty', models.ForeignKey(blank=True, help_text='Drives the faculty result analysis.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mark_entries', to='Dashboard.staff')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mark_entries', to='Dashboard.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mark_entries', to='Dashboard.subject')),
            ],
            options={
                'verbose_name_plural': 'mark entries',
                'ordering': ['-examdate', 'subject__order'],
                'unique_together': {('student', 'subject', 'exam_type', 'examdate')},
            },
        ),
    ]
