# Generated by Django 6.0.1 on 2026-09-25 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0007_backfill_attendance_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(help_text='Internal id used in code. Do not change once set.', unique=True)),
                ('name', models.CharField(max_length=80)),
                ('description', models.CharField(blank=True, max_length=250)),
                ('is_enabled', models.BooleanField(default=True, help_text='Off hides the screen and blocks its URL, even if someone types it directly.')),
                ('show_when_disabled', models.BooleanField(default=False, help_text='Leave the item visible in the menu with a padlock, so the client can see the feature exists. Off hides it completely.', verbose_name='Show as locked when disabled')),
                ('is_billable', models.BooleanField(default=False, help_text='Marker for your own billing. Has no effect on access.', verbose_name='Chargeable add-on')),
                ('notes', models.CharField(blank=True, help_text='Private note. Never shown to the client.', max_length=250)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
    ]
