# Generated by Django 3.2.3 on 2021-07-07 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=100)),
                ('school', models.TextField()),
                ('contact', models.BigIntegerField()),
                ('slocation', models.CharField(max_length=20)),
                ('ystudy', models.CharField(max_length=10)),
                ('mailid', models.EmailField(max_length=200)),
            ],
        ),
    ]
