# Generated by Django 3.2.3 on 2021-07-07 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admision',
            name='mailid',
            field=models.EmailField(max_length=100),
        ),
    ]
