# Generated by Django 3.2.3 on 2021-11-30 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_admision_mailid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fupload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empid', models.CharField(max_length=20)),
                ('mtype', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('comment', models.TextField()),
                ('fdata', models.FileField(upload_to='uploadedfiles/facultyportal/%y/%m/%d/')),
            ],
        ),
    ]
