# Generated by Django 3.2.3 on 2021-11-30 12:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_fupload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fupload',
            name='date',
        ),
        migrations.AddField(
            model_name='fupload',
            name='update',
            field=models.DateField(default=datetime.date(2021, 11, 30)),
        ),
    ]
