# Generated by Django 3.2.3 on 2021-11-30 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20211130_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fupload',
            name='update',
            field=models.DateField(auto_now_add=True),
        ),
    ]
