# Generated by Django 3.2.3 on 2021-11-30 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0001_initial'),
        ('home', '0005_alter_fupload_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fupload',
            name='empid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Dashboard.staff'),
        ),
    ]
