# Generated by Django 3.2.3 on 2022-05-28 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_fupload_empid'),
    ]

    operations = [
        migrations.AddField(
            model_name='admision',
            name='scourse',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
