# Generated by Django 6.0.1 on 2026-09-02 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='Used in URLs. Changing this changes the page address.', unique=True)),
                ('name', models.CharField(help_text='Full public name, e.g. "London Kids International Play School".', max_length=120)),
                ('short_name', models.CharField(help_text='Used in the navbar and page titles, e.g. "London Kids".', max_length=60)),
                ('descriptor', models.CharField(blank=True, help_text='e.g. "A Unit of Wisdom Group of Institutions".', max_length=150)),
                ('tagline', models.CharField(blank=True, max_length=200)),
                ('welcome_heading', models.CharField(blank=True, max_length=200)),
                ('intro', models.TextField(blank=True, help_text='Hero paragraph(s). Blank line separates paragraphs.')),
                ('about', models.TextField(blank=True, help_text='"About Us" body. Blank line separates paragraphs.')),
                ('vision', models.TextField(blank=True)),
                ('mission', models.TextField(blank=True)),
                ('admissions_note', models.TextField(blank=True, help_text='Shown in the admissions call-to-action.')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='brand/')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. "Wisdom Coaching Centre - Gandhi Nagar".', max_length=120)),
                ('address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, help_text='Comma-separate multiple numbers.', max_length=60)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('whatsapp_number', models.CharField(blank=True, help_text='Digits only, with country code if known.', max_length=20)),
                ('maps_url', models.URLField(blank=True, max_length=300)),
                ('facebook_url', models.URLField(blank=True, max_length=300)),
                ('instagram_url', models.URLField(blank=True, max_length=300)),
                ('youtube_url', models.URLField(blank=True, max_length=300)),
                ('whatsapp_channel_url', models.URLField(blank=True, max_length=300)),
                ('payment_qr', models.ImageField(blank=True, null=True, upload_to='branch/qr/')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='institutions.brand')),
            ],
            options={
                'verbose_name_plural': 'branches',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('age_range', models.CharField(blank=True, help_text='e.g. "2-3 Years". Leave blank if not age-based.', max_length=60)),
                ('intro', models.TextField(blank=True)),
                ('focus_areas', models.TextField(blank=True, help_text='One focus area per line.')),
                ('image', models.ImageField(blank=True, null=True, upload_to='programs/')),
                ('admissions_open', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='institutions.brand')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BrandSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(help_text='Anchor id used in the page URL, e.g. "facilities".')),
                ('title', models.CharField(max_length=150)),
                ('intro', models.TextField(blank=True)),
                ('bullets', models.TextField(blank=True, help_text='One item per line.')),
                ('outro', models.TextField(blank=True)),
                ('layout', models.CharField(choices=[('pills', 'Pills - short items, wrapped chips'), ('cards', 'Cards - one card per item'), ('feature', 'Feature - highlighted panel with intro')], default='pills', max_length=10)),
                ('is_published', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='institutions.brand')),
            ],
            options={
                'ordering': ['order', 'title'],
                'unique_together': {('brand', 'key')},
            },
        ),
    ]
