# Generated by Django 6.0.1 on 2026-09-02 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0005_seed_wcc_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandsection',
            name='nav_label',
            field=models.CharField(blank=True, help_text='Short label for the top menu, e.g. "Why Us". Leave blank to keep this section out of the menu -- full section titles are too long for a navbar.', max_length=30),
        ),
    ]
